/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AboutView': RouteRecordInfo<'/AboutView', '/about', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/ArticlesView': RouteRecordInfo<'/ArticlesView', '/articles', Record<never, never>, Record<never, never>>,
    '/DailyView': RouteRecordInfo<'/DailyView', '/daily', Record<never, never>, Record<never, never>>,
    '/RecordView': RouteRecordInfo<'/RecordView', '/records', Record<never, never>, Record<never, never>>,
    '/ShareView': RouteRecordInfo<'/ShareView', '/share', Record<never, never>, Record<never, never>>,
    '/ShopView': RouteRecordInfo<'/ShopView', '/shop', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/AboutView.vue': {
      routes: '/AboutView'
      views: never
    }
    'src/pages/admin/index.vue': {
      routes: '/admin/'
      views: never
    }
    'src/pages/ArticlesView.vue': {
      routes: '/ArticlesView'
      views: never
    }
    'src/pages/DailyView.vue': {
      routes: '/DailyView'
      views: never
    }
    'src/pages/RecordView.vue': {
      routes: '/RecordView'
      views: never
    }
    'src/pages/ShareView.vue': {
      routes: '/ShareView'
      views: never
    }
    'src/pages/ShopView.vue': {
      routes: '/ShopView'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
